name: Check Pull Request CI Status

on: # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

permissions:
  checks: read
  statuses: read

jobs:
  all-jobs-are-green:
    runs-on: ubuntu-latest
    timeout-minutes: 60
    steps:
      - name: Run Ensure CI Success
        uses: DataDog/ensure-ci-success@b0d931ac77c810490e61964c321103040eef888e # v2.3.0
        with:
          # How long to wait before we start checking the job status
          # GitHub's API has a limit, so this helps avoid making too many calls
          # Note: If the job is retried, we'll check it once right away before waiting
          # Why 3 minutes: If a job fails, the all-green job also fails. If the original
          # job is retried and the all-green job is retried, the all-green job will not
          # see that all jobs are successful on the first invocation (since the failed
          # job is still running). But because we are not running the full test suite,
          # we do not want to wait 15 minutes to check if everything passed.
          initial-delay-seconds: 180

          # How long to wait between each check
          # Total wait time: 180s + (87 retries Ã— 60s) = 5400s = 1.5 hours
          max-retries: 87

          # Sleep time between each check (default: 60 seconds)
          # polling-interval-seconds: "60"

          # Excluded jobs names, each line is a regular expression that must fullm atch the job name
          # it's currently empty, but here is an example:
          # ignored-name-patterns: |
          #   .*-test-flaky
          #   useless-job
