name: Lock Dependencies

on: # yamllint disable-line rule:truthy
  pull_request:
    branches:
      - master

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

# Default permissions for all jobs
permissions: {}

jobs:
  dependency:
    name: Dependency changes
    runs-on: ubuntu-24.04
    outputs:
      changes: ${{ steps.changes.outputs.dependencies }}
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - uses: dorny/paths-filter@de90cc6fb38fc0963ad72b210f1f284cd68cea36 # v3.0.2
        id: changes
        with:
          filters: .github/dependency_filters.yml

  lock:
    runs-on: ubuntu-24.04
    needs: dependency
    if: ${{ needs.dependency.outputs.changes == 'true' }}
    strategy:
      fail-fast: false
      matrix:
        engine:
          # ADD NEW RUBIES HERE
          - name: ruby
            version: "4.0"
          - name: ruby
            version: "3.4"
          - name: ruby
            version: "3.3"
          - name: ruby
            version: "3.2"
          - name: ruby
            version: "3.1"
          - name: ruby
            version: "3.0"
          - name: ruby
            version: "2.7"
          - name: ruby
            version: "2.6"
          - name: ruby
            version: "2.5"
          - name: jruby
            version: "9.4"
          - name: jruby
            version: "9.3"
          - name: jruby
            version: "9.2"
          - name: jruby
            version: "10.0"
    container:
      image: ghcr.io/datadog/images-rb/engines/${{ matrix.engine.name }}:${{ matrix.engine.version }}-gnu-gcc
      env:
        BUNDLE_WITHOUT: check
    steps:
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: false
      - run: |
          ruby -v
          gem -v
          bundler -v
      - run: bundle install
      - run: bundle exec rake dependency:generate
      - run: bundle exec rake dependency:lock
      - uses: actions/upload-artifact@b7c566a772e6b6bfb58ed0dc250532a479d7789f # v6.0.0
        with:
          name: lock-dependency-${{ github.run_id }}-${{ matrix.engine.name }}-${{ matrix.engine.version }}
          path: gemfiles/${{ matrix.engine.name }}_${{ matrix.engine.version }}*
          retention-days: 1

  commit:
    name: Commit changes
    needs: lock
    runs-on: ubuntu-24.04
    steps:
      - name: Generate GitHub App Token
        id: generate-token
        uses: actions/create-github-app-token@29824e69f54612133e76f7eaac726eef6c875baf # v2.2.1
        with:
          app-id: ${{ secrets.APP_ID }}
          private-key: ${{ secrets.APP_PRIVATE_KEY }}
      - uses: actions/checkout@de0fac2e4500dabe0009e67214ff5f5447ce83dd # v6.0.2
        with:
          persist-credentials: true # required for `git` operations (commit & push) at later steps
          token: ${{ steps.generate-token.outputs.token }}
      - uses: actions/download-artifact@37930b1c2abaa49bbe596cd826c3c89aef350131 # v7.0.0
        with:
          path: gemfiles
          pattern: lock-dependency-${{ github.run_id }}-*
          merge-multiple: true
      # FIXME: The ghcommit-action does not pick up untracked/unstaged files
      #        https://github.com/planetscale/ghcommit-action/issues/43
      - name: Stage changes
        run: git add gemfiles
      - run: git diff --cached --color=always
      - name: Commit changes
        uses: planetscale/ghcommit-action@25309d8005ac7c3bcd61d3fe19b69e0fe47dbdde # v0.2.20
        with:
          repo: ${{ github.repository }}
          branch: ${{ github.head_ref }}
          file_pattern: "gemfiles/*"
          commit_message: "[ðŸ¤–] Lock Dependency: https://github.com/${{ github.repository }}/actions/runs/${{ github.run_id }}"
        env:
          GITHUB_TOKEN: ${{ steps.generate-token.outputs.token }}

  complete:
    name: Lock Dependencies (complete)
    runs-on: ubuntu-24.04
    needs:
      - commit
    steps:
      - run: echo "DONE!"
