name: Test macOS
on:
  push:
    branches:
      - "**"
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]
jobs:
  test-macos:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-13
        ruby:
          - '3.0'
          - '3.1'
          - '3.2'
          - '3.3'
          - '3.4'
          # ADD NEW RUBIES HERE
    name: Test (${{ matrix.os }}, ${{ matrix.ruby }})
    runs-on: ${{ matrix.os }}
    env:
      SKIP_SIMPLECOV: 1
      DD_INSTRUMENTATION_TELEMETRY_ENABLED: false
      DD_REMOTE_CONFIGURATION_ENABLED: false
    steps:
      - uses: actions/checkout@v4
      # bundler appears to match both prerelease and release rubies when we
      # want the former only. relax the constraint to allow any version for
      # head rubies
      - if: ${{ matrix.ruby == 'head' }}
        run: sed -i~ -e '/spec\.required_ruby_version/d' datadog.gemspec
      - uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          rubygems: 3.3.26
          bundler: 2.3.26 # needed to fix issue with steep on Ruby 3.0/3.1
      # Specify gem version for 3.4 because default version (3.6.0.dev)
      # leads to an incorrect gem root path
      - if: ${{ matrix.ruby == '3.3' || matrix.ruby == '3.4' }}
        run: gem update --system 3.5.21
      - run: bundle install
      - run: bundle exec rake spec:main
