name: Test macOS
on: [push]
jobs:
  test-macos:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-latest
        ruby:
          - '2.1'
          - '2.2'
          - '2.3'
          - '2.4'
          - '2.5'
          - '2.6'
          - '2.7'
          - '3.0'
          - '3.1'
          - '3.2'
          # ADD NEW RUBIES HERE
    name: Test (${{ matrix.os }}, ${{ matrix.ruby }})
    runs-on: ${{ matrix.os }}
    env:
      SKIP_SIMPLECOV: 1
      DD_INSTRUMENTATION_TELEMETRY_ENABLED: false
    steps:
      - uses: actions/checkout@v3
      # bundler appears to match both prerelease and release rubies when we
      # want the former only. relax the constraint to allow any version for
      # head rubies
      - if: ${{ matrix.ruby == 'head' }}
        run: sed -i~ -e '/spec\.required_ruby_version/d' ddtrace.gemspec
      - uses: ruby/setup-ruby@31a7f6d628878b80bc63375a93ae079ec50a1601 # v1.143.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
          bundler: latest # needed to fix issue with steep on Ruby 3.0/3.1
      - run: bundle exec rake spec:main
