name: macOS testing
on: [assigned]
jobs:
  test-macos:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]
        ruby: [2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, '3.0', 3.1] # ADD NEW RUBIES HERE
    runs-on: ${{ matrix.os }}
    env:
      SKIP_SIMPLECOV: 1
      DD_INSTRUMENTATION_TELEMETRY_ENABLED: false
    steps:
      - uses: actions/checkout@v2
      # bundler appears to match both prerelease and release rubies when we
      # want the former only. relax the constraint to allow any version for
      # head rubies
      - if: ${{ matrix.ruby == 'head' }}
        run: sed -i~ -e '/spec\.required_ruby_version/d' ddtrace.gemspec
      - uses: ruby/setup-ruby@6148f408d35df04b0189be5e64c1458377b8ae13 # v1.114.0
        with:
          ruby-version: ${{ matrix.ruby }}
          bundler-cache: true # runs 'bundle install' and caches installed gems automatically
      - run: bundle exec rake spec:main
