name: Test macOS

on: # yamllint disable-line rule:truthy
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

# Default permissions for all jobs
permissions: {}

jobs:
  test-macos:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-15
        ruby:
          - '3.0'
          - '3.1'
          - '3.2'
          - '3.3'
          - '3.4'
          - '4.0'
          # ADD NEW RUBIES HERE
    name: Test (${{ matrix.os }}, ${{ matrix.ruby }})
    runs-on: ${{ matrix.os }}
    env:
      SKIP_SIMPLECOV: 1
      DD_INSTRUMENTATION_TELEMETRY_ENABLED: false
      DD_REMOTE_CONFIGURATION_ENABLED: false
    steps:
      - uses: actions/checkout@1af3b93b6815bc44a9784bd300feb67ff0d1eeb3 # v6.0.0
        with:
          persist-credentials: false
      # bundler appears to match both prerelease and release rubies when we
      # want the former only. relax the constraint to allow any version for
      # head rubies
      - if: ${{ matrix.ruby == 'head' }}
        run: sed -i~ -e '/spec\.required_ruby_version/d' datadog.gemspec
      - uses: ruby/setup-ruby@8aeb6ff8030dd539317f8e1769a044873b56ea71 # v1.268.0
        with:
          ruby-version: ${{ matrix.ruby }}
      - run: |
          which ruby
          ruby --version
          which gem
          gem --version
          which bundle
          bundle --version
      - run: bundle install
      - run: bundle exec rake spec:main

  complete:
    name: Test macOS (complete)
    runs-on: ubuntu-24.04
    needs:
      - test-macos
    steps:
      - run: echo "DONE!"
