name: Test macOS
on:
  push:
    branches:
      - "**"
  pull_request:
    # The branches below must be a subset of the branches above
    branches: [ master ]
jobs:
  test-macos:
    strategy:
      fail-fast: false
      matrix:
        os:
          - macos-13
        ruby:
          - '2.2'
          - '2.3'
          - '2.4'
          - '2.5'
          - '2.6'
          - '2.7'
          - '3.0'
          - '3.1'
          - '3.2'
          - '3.3'
          # ADD NEW RUBIES HERE
    name: Test (${{ matrix.os }}, ${{ matrix.ruby }})
    runs-on: ${{ matrix.os }}
    env:
      SKIP_SIMPLECOV: 1
      DD_INSTRUMENTATION_TELEMETRY_ENABLED: false
      DD_REMOTE_CONFIGURATION_ENABLED: false
    steps:
      - uses: actions/checkout@v4
      # bundler appears to match both prerelease and release rubies when we
      # want the former only. relax the constraint to allow any version for
      # head rubies
      - if: ${{ matrix.ruby == 'head' }}
        run: sed -i~ -e '/spec\.required_ruby_version/d' ddtrace.gemspec
      - if: ${{ matrix.ruby == '2.2' }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          rubygems: 2.7.11
          bundler: 1.17.3
      - if: ${{ matrix.ruby != '2.2' }}
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: ${{ matrix.ruby }}
          rubygems: 3.3.26
          bundler: 2.3.26 # needed to fix issue with steep on Ruby 3.0/3.1
      - run: bundle install
      - run: bundle exec rake spec:main
